### ISSUE TITLE
Opening the levelloader Enable Content Configuration will cause the map to be locked

### ISSUE THREAD

**Issue by 1410677474** [ImpulsiveLad/NarrowMoonChoices#1]
My random startup requires levelloader.cfg to modify the map, which will cause me to be unable to use this module

**Comment by ImpulsiveLass** [comment]
What is the levelloader Enable Content Configuration? Are you setting the config in game somehow?

**Comment by 1410677474** [comment]
![e8e32ca8ddce9660f592edbf725dab0](https://github.com/ImpulsiveLad/NarrowMoonChoices/assets/163803538/df6e8dac-22a7-4587-b9cb-124faed48bff)
![0aa9c2b837b4389f73cb954ecf88373](https://github.com/ImpulsiveLad/NarrowMoonChoices/assets/163803538/a91f6ff1-9a30-4a7c-9b3a-0da28c88f85f)

**Comment by 1410677474** [comment]
> What is the levelloader Enable Content Configuration? Are you setting the config in game somehow?

This way

**Comment by ImpulsiveLass** [comment]
I don't understand what this has to do with my mod. From my understanding you messed with LLL settings and lost some data?

If you really mean that setting that to true makes it 'locked' firstly you check through logs that it is meant to be unlocked yes?

Like if you have only 3 total moons (default) set to getting unlocked then it could just not be unlocking that exact moon. Changing that value to true effects nothing besides allowing you to set values on launch, this does not matter as all of those values will be modified later by my mod.

**Comment by ImpulsiveLass** [comment]
If what you want if for x moons to be always available, or never available and untouched by this mod. There are config lists to do that.

IE if you want to always have the vanilla moons and only have modded moons be shuffled you would put `Gordion,Experimentation,Assurance,Vow,Offense,March,Adamance,Dine,Rend,Titan,Embrion,Artifice` into the IgnoreMoons setting.
