### ISSUE TITLE
[Error] Shuffle does't work

### ISSUE THREAD

**Issue by Seryt1000** [ImpulsiveLad/NarrowMoonChoices#4]
Mod doesn't work and sends errors:

[15:10:54.7595865] [Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'WeatherRegistry, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
Selenes_Choice.HideMoonsOnGameOver+<WaitOnDeath>d__2.MoveNext () (at C:/Users/scpki/source/repos/Selenes_Choice/Selenes_Choice/NarrowOnGameOver.cs:21)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

[15:10:54.7595865] [Error  : Unity Log] FileNotFoundException: Could not load file or assembly 'WeatherRegistry, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies.
Stack trace:
Selenes_Choice.HideMoonsOnGameOver+<WaitOnDeath>d__2.MoveNext () (at C:/Users/scpki/source/repos/Selenes_Choice/Selenes_Choice/NarrowOnGameOver.cs:21)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

Seem's that issue is with weather registry, but no mod differs it.

Version of game: V62, fresh save
Only vanilla moons but all set to be free with additional mod.
(If you need I will try to give more info)

Upd: tested on fully clear modpack, still not working, so no incompability with other mods

**Comment by ImpulsiveLass** [comment]
Tell me more, do you have WeatherRegistry?
Does it load when you have it installed?

**Comment by ImpulsiveLass** [comment]
This should be fixed in 2.0.1
I never used a soft dep before and did a wrong 💀 

If you were getting this error every shuffle because WR wasn't installed then yeah it should be patched now, get back to me plz.

**Comment by Seryt1000** [comment]
Everything works now! Thanks!
(Sorry for not aswering earlier, time zones)
