### ISSUE TITLE
[Bug] no selene moons are shown when free moon pool is empty + routing to a locked moon breaks the console

### ISSUE THREAD

**Issue by JohnMetroid** [ImpulsiveLad/NarrowMoonChoices#5]
I confirmed that both bugs are still present in 2.0.1. I would have reopened the previous ticket, but it appears to be locked

https://github.com/ImpulsiveLad/NarrowMoonChoices/issues/3

**Comment by ImpulsiveLass** [comment]
You have 0 free moons in your entire modpack?

**Comment by ImpulsiveLass** [comment]
Just trying to clarify that your issue is that you have literally no free moons because if so, then yes it will break since its currently coded to use the first free moon it selects but I can make it do that with a separate paid moon if it must.

`Routing to a locked moon breaks the console`?
You can't route to a locked moon, what does this mean?
Are you using some terminal mod that doesn't have LLL integration?

**Comment by JohnMetroid** [comment]
I'm happy to address anything that's unclear, but it's the same issues that were reported thoroughly in the previous ticket

For issues 1: When free moons are removed from a mod pack or 0 free moons are present, selene's choice will break and not populate any moon choices.  The error thrown is the same that was reported before

```
[17:09:54.2573546] [Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <787acc3c9a4c471ba7d971300105af24>:IL_0009)
Selenes_Choice.HideMoonsOnStart.ProcessData () (at <cad98e21beac4641ac12ed2fbca2e1f4>:IL_0143)
Selenes_Choice.HideMoonsOnStart+<WaitOnStart>d__5.MoveNext () (at <cad98e21beac4641ac12ed2fbca2e1f4>:IL_0040)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)

[17:09:54.2583559] [Error  : Unity Log] ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
Stack trace:
System.Collections.Generic.List`1[T].get_Item (System.Int32 index) (at <787acc3c9a4c471ba7d971300105af24>:IL_0009)
Selenes_Choice.HideMoonsOnStart.ProcessData () (at <cad98e21beac4641ac12ed2fbca2e1f4>:IL_0143)
Selenes_Choice.HideMoonsOnStart+<WaitOnStart>d__5.MoveNext () (at <cad98e21beac4641ac12ed2fbca2e1f4>:IL_0040)
UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <e27997765c1848b09d8073e5d642717a>:IL_0026)
```
and can presumably be bugfixed by adding a check that the free moon list isn't blank, in which case the free moon choices would be skipped before moving onto other choices.

For issue 2:

There is no special setup needed.  Simply type "route [locked moon]" and you will softlock the terminal with the afore-mentioned bug.  The terminal will then need to be exited and reentered before it reacts to any commands.

```
[18:04:36.8721943] [Info   : Unity Log] result: toilationRoute
[18:04:36.8761952] [Info   :   Console] Run text post process
[18:04:39.5427969] [Error  : Unity Log] IndexOutOfRangeException: Index was outside the bounds of the array.
Stack trace:
(wrapper dynamic-method) Terminal.DMD<Terminal::OnSubmit>(Terminal)
UnityEngine.Events.InvokableCall.Invoke () (at <e27997765c1848b09d8073e5d642717a>:IL_0010)
UnityEngine.Events.UnityEvent`1[T0].Invoke (T0 arg0) (at <e27997765c1848b09d8073e5d642717a>:IL_0049)
TMPro.TMP_InputField.SendOnEndEdit () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_000E)
TMPro.TMP_InputField.ReleaseSelection () (at <9baa8119dbcd498f902c1a92f10843c1>:IL_001B)
TMPro.TMP_InputField.DeactivateInputField (System.Boolean clearSelection) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_00B0)
TMPro.TMP_InputField.OnUpdateSelected (UnityEngine.EventSystems.BaseEventData eventData) (at <9baa8119dbcd498f902c1a92f10843c1>:IL_007C)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IUpdateSelectedHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <17de86d66286445fa95af59fa8fa644d>:IL_0000)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <17de86d66286445fa95af59fa8fa644d>:IL_0067)
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:<LogException>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:36)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass28_0:<wrapCallback>b__0() (at ./src/Wrappers/Unity/AsyncLoggerWrapper.cs:136)
AsyncLoggers.Wrappers.JobWrapper:LogWorker() (at ./src/Wrappers/JobWrapper.cs:84)
AsyncLoggers.Wrappers.LogJob:Execute() (at ./src/Wrappers/JobWrapper.cs:68)
Unity.Jobs.JobStruct`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)
```

This is unrelated to LLL, it's a selene's choice bug.  I confirmed that upon your request last time.

Thanks

edit: here's a gif to help illustrate issue 2

https://i.imgur.com/L1p0pYx.gif

**Comment by ImpulsiveLass** [comment]
I can fix the first thing, just never though people would have no free moons, guess I’ll just make the safety moon be a random paid moon and skip the free loops then.
I’ll have to test the other myself, it’s very bizarre

**Comment by JohnMetroid** [comment]
>I can fix the first thing, just never though people would have no free moons, guess I’ll just make the safety moon be a random paid moon and skip the free loops then.

I meant to ask, is the thing you're calling the "safety moon" the same moon that gets routed to after the company sell day?  Is it configurable in any way?

> I’ll have to test the other myself, it’s very bizarre

If you need any more info on that just let me know and I can double check.  Based on the checks I did last time, it was completely different behavior from locking/hiding a moon through LLL/etc.
